### ISSUE TITLE
Continuous build :  `CXXABI_1.3.11' and `ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by julonexus** [linuxdeploy/linuxdeploy#142]
Hi, since today (06/08/2020), the use of linuxdeploy-x86_64 on Debian9 from continuous build lead to this error and break CI works:

./AppImageDir/AppBin/linuxdeploy-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./AppImageDir/AppBin/linuxdeploy-x86_64.AppImage)
./AppImageDir/AppBin/linuxdeploy-x86_64.AppImage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_linuxdcIFxK2/usr/bin/../lib/libpng16.so.16)
-- Code Signing of AppImage
appimagetool, continuous build (commit 0880085), build 2133 built on 2020-07-09 12:25:52 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
Desktop file not found, aborting

Have you changed anything?

**Comment by TheAssassin** [comment]
Working on it. I've switched the CI to build fully static binaries (see #141 for more information), but it seems the CI doesn't create static binaries while it works locally. Working on a fix already.

If you need working binaries, please use the old builds: https://artifacts.assassinate-you.net/artifactory/list/linuxdeploy/travis-456/

I'll keep this issue updated.

**Comment by julonexus** [comment]
Great to know, thanks

**Comment by TheAssassin** [comment]
I started a kind of "data rentention" of all AppImage related software builds to have "backups" in exactly these cases.

**Comment by TheAssassin** [comment]
Fixed to some extent in the upcoming continuous build. I've basically had to build my own subprocessing library, which is currently beta-grade (tested extensively, I think I caught most bugs), because the previously used one didn't work when linked statically (for some reason I couldn't understand after a few hours of debugging...).

linuxdeploy is now built statically, just like most of its dependencies. Still fiddling with binutils (the `strip` contained in the AppImage is built as-statically-as-possible, basically, still depends on the glibc and doesn't run on CentOS6 -- not really a problem, though, `strip` is just a minor optimization to reduce the size of the AppImage and linuxdeploy can continue to run if `strip` calls fail).

**Comment by TheAssassin** [comment]
Found a way to build static binaries of `strip`. All issues should be fixed. Please open new issues if you encounter any problems with the new setup.

**Comment by julonexus** [comment]
Ok, there is still an issue with the desktop file. I'm going to open a new issue for that
